export type EeffocTemplateCategory =
  | "classic"
  | "limited_drop"
  | "time_window"
  | "friend"
  | "repeat_visitor"
  | "discovery"
  | "premium"
  | "weather"
  | "weekly_ritual"
  | "creator"
  | "custom";

export type EeffocTemplate = {
  id: string;
  category: EeffocTemplateCategory;
  title: string;
  emoji: string;
  description: string;
  reward_description: string;
  points_reward: number;
  requirements: string;
  hashtag: string;
  durationDays: number;
  max_participants: number | null;
  fulfillment_mode: "check_in" | "social_proof" | "hybrid";
  social_requirements?: {
    platforms?: string[];
    caption_template?: string;
    media_hints?: string;
  };
};

export const EEFFOC_CATEGORY_LABEL_KEYS: Record<EeffocTemplateCategory, string> = {
  classic: "partnerCampaignsPage.categories.classic",
  limited_drop: "partnerCampaignsPage.categories.limitedDrop",
  time_window: "partnerCampaignsPage.categories.timeWindow",
  friend: "partnerCampaignsPage.categories.friend",
  repeat_visitor: "partnerCampaignsPage.categories.repeatVisitor",
  discovery: "partnerCampaignsPage.categories.discovery",
  premium: "partnerCampaignsPage.categories.premium",
  weather: "partnerCampaignsPage.categories.weather",
  weekly_ritual: "partnerCampaignsPage.categories.weeklyRitual",
  creator: "partnerCampaignsPage.categories.creator",
  custom: "partnerCampaignsPage.categories.custom",
};

export const EEFFOC_CATEGORY_GROUPS: {
  id: string;
  labelKey: string;
  categories: EeffocTemplateCategory[];
}[] = [
  {
    id: "essentials",
    labelKey: "campaignWizard.categoryGroups.essentials",
    categories: ["classic", "discovery", "custom"],
  },
  {
    id: "engagement",
    labelKey: "campaignWizard.categoryGroups.engagement",
    categories: ["friend", "repeat_visitor", "creator"],
  },
  {
    id: "timing",
    labelKey: "campaignWizard.categoryGroups.timing",
    categories: ["limited_drop", "time_window", "weekly_ritual", "weather"],
  },
  {
    id: "premium",
    labelKey: "campaignWizard.categoryGroups.premium",
    categories: ["premium"],
  },
];

export const EEFFOC_TEMPLATES: EeffocTemplate[] = [
  {
    id: "we_give_eeffoc",
    category: "classic",
    title: "We give EEFFOC!",
    emoji: "☕",
    description: "The classic, free coffee for one approved social post. Simple, memorable, on-brand.",
    reward_description: "1 free coffee of your choice",
    points_reward: 20,
    requirements: "Post on Instagram or TikTok tagging the café with the campaign hashtag.",
    hashtag: "#WeGiveEEFFOC",
    durationDays: 30,
    max_participants: 200,
    fulfillment_mode: "social_proof",
    social_requirements: {
      platforms: ["instagram_post", "instagram_story", "tiktok"],
      caption_template: "Coffee moment at {shop_name}! {hashtag}",
      media_hints: "Show your drink, the vibe, or your first sip.",
    },
  },
  {
    id: "post_and_pour",
    category: "classic",
    title: "Post and pour, what EEFFOC",
    emoji: "📸",
    description: "Post first, sip second, a clear action-reward loop explorers understand instantly.",
    reward_description: "Free drink after approved post",
    points_reward: 25,
    requirements: "Share a photo or story with our hashtag before ordering.",
    hashtag: "#PostAndPour",
    durationDays: 21,
    max_participants: 150,
    fulfillment_mode: "social_proof",
    social_requirements: {
      platforms: ["instagram_post", "instagram_story", "tiktok"],
      caption_template: "Post & Pour at {shop_name} {hashtag}",
    },
  },
  {
    id: "scan_post_sip",
    category: "classic",
    title: "Scan. Post. Sip. EEFFOC.",
    emoji: "📱",
    description: "Perfect for counter QR displays, scan, post, enjoy.",
    reward_description: "1 complimentary drink",
    points_reward: 15,
    requirements: "Scan café QR, post proof, redeem at counter.",
    hashtag: "#ScanPostSip",
    durationDays: 30,
    max_participants: 250,
    fulfillment_mode: "hybrid",
    social_requirements: {
      platforms: ["instagram_story", "instagram_post"],
      caption_template: "Scan. Post. Sip. at {shop_name} {hashtag}",
    },
  },
  {
    id: "flash_eeffoc",
    category: "limited_drop",
    title: "Flash EEFFOC",
    emoji: "⚡",
    description: "A short limited-time drop for slow hours or surprise buzz.",
    reward_description: "Free espresso, today only",
    points_reward: 15,
    requirements: "First 30 explorers today. Check in before they're gone.",
    hashtag: "#FlashEEFFOC",
    durationDays: 3,
    max_participants: 30,
    fulfillment_mode: "check_in",
  },
  {
    id: "espresso_sprint",
    category: "limited_drop",
    title: "No EEFFOC, but Espresso",
    emoji: "🏃",
    description: "Fast, limited, first 20 explorers today win.",
    reward_description: "Free espresso shot",
    points_reward: 10,
    requirements: "Be among the first 20 check-ins today.",
    hashtag: "#EspressoSprint",
    durationDays: 7,
    max_participants: 20,
    fulfillment_mode: "check_in",
  },
  {
    id: "golden_eeffoc",
    category: "premium",
    title: "Golden EEFFOC",
    emoji: "🏆",
    description: "Premium drink for explorers who go the extra mile on social.",
    reward_description: "Signature drink upgrade",
    points_reward: 35,
    requirements: "High-quality post with drink close-up and hashtag.",
    hashtag: "#GoldenEEFFOC",
    durationDays: 14,
    max_participants: 50,
    fulfillment_mode: "social_proof",
    social_requirements: {
      platforms: ["instagram_post", "tiktok"],
      caption_template: "Golden moment at {shop_name} {hashtag}",
      media_hints: "Film the pour, latte art, or signature drink.",
    },
  },
  {
    id: "happy_eeffoc_hour",
    category: "time_window",
    title: "Happy EEFFOC Hour",
    emoji: "🕒",
    description: "Morning or afternoon traffic boost, coffee happy hour.",
    reward_description: "50% off any drink",
    points_reward: 10,
    requirements: "Check in between 15:00–17:00 on weekdays.",
    hashtag: "#HappyEEFFOCHour",
    durationDays: 21,
    max_participants: 120,
    fulfillment_mode: "check_in",
  },
  {
    id: "morning_eeffoc_rush",
    category: "time_window",
    title: "Morning EEFFOC Rush",
    emoji: "🌅",
    description: "Catch commuters before work, 07:00–10:00.",
    reward_description: "Free filter coffee before 10am",
    points_reward: 12,
    requirements: "Check in weekday mornings before 10:00.",
    hashtag: "#MorningEEFFOC",
    durationDays: 14,
    max_participants: 80,
    fulfillment_mode: "check_in",
  },
  {
    id: "lunch_break_eeffoc",
    category: "time_window",
    title: "Lunch Break EEFFOC",
    emoji: "🥪",
    description: "Midday reward for office explorers on lunch break.",
    reward_description: "Free americano with any pastry",
    points_reward: 12,
    requirements: "Check in between 11:30–14:00.",
    hashtag: "#LunchBreakEEFFOC",
    durationDays: 21,
    max_participants: 100,
    fulfillment_mode: "check_in",
  },
  {
    id: "buddy_eeffoc",
    category: "friend",
    title: "Buddy EEFFOC",
    emoji: "👯",
    description: "Bring a friend, both explorers get rewarded.",
    reward_description: "Buy one, friend gets one free",
    points_reward: 20,
    requirements: "Two explorers check in together within 5 minutes.",
    hashtag: "#BuddyEEFFOC",
    durationDays: 14,
    max_participants: 100,
    fulfillment_mode: "check_in",
  },
  {
    id: "double_eeffoc",
    category: "friend",
    title: "Double EEFFOC",
    emoji: "✌️",
    description: "Two rewards or double exposure, post together!",
    reward_description: "2-for-1 on any coffee drink",
    points_reward: 18,
    requirements: "Post a joint photo tagging both explorers and the café.",
    hashtag: "#DoubleEEFFOC",
    durationDays: 14,
    max_participants: 80,
    fulfillment_mode: "hybrid",
    social_requirements: {
      platforms: ["instagram_post", "instagram_story"],
      caption_template: "Double EEFFOC with a friend at {shop_name} {hashtag}",
    },
  },
  {
    id: "first_sip_eeffoc",
    category: "repeat_visitor",
    title: "First Sip EEFFOC",
    emoji: "🌱",
    description: "Welcome new explorers with a friendly first-visit reward.",
    reward_description: "Free drink for first-time visitors",
    points_reward: 25,
    requirements: "First check-in at this café on CO:FE(X).",
    hashtag: "#FirstSipEEFFOC",
    durationDays: 30,
    max_participants: 200,
    fulfillment_mode: "check_in",
  },
  {
    id: "loyal_eeffoc",
    category: "repeat_visitor",
    title: "Loyal EEFFOC",
    emoji: "💛",
    description: "Reward returning explorers who keep coming back.",
    reward_description: "Free pastry on your 5th visit",
    points_reward: 30,
    requirements: "Complete 5 check-ins during the campaign period.",
    hashtag: "#LoyalEEFFOC",
    durationDays: 60,
    max_participants: 150,
    fulfillment_mode: "check_in",
  },
  {
    id: "cappuccino_club",
    category: "repeat_visitor",
    title: "EEFFOC...cinnooo...",
    emoji: "🤎",
    description: "Community campaign for regulars who love your foam art.",
    reward_description: "Free cappuccino after 3 visits",
    points_reward: 20,
    requirements: "Three verified check-ins this month.",
    hashtag: "#CappuccinoClub",
    durationDays: 30,
    max_participants: 120,
    fulfillment_mode: "check_in",
  },
  {
    id: "bean_hunt_eeffoc",
    category: "discovery",
    title: "Bean Hunt EEFFOC",
    emoji: "🗺️",
    description: "Map exploration drop, appears as a special location for discoverers.",
    reward_description: "Surprise free drink",
    points_reward: 25,
    requirements: "Find us on the campaign map and check in.",
    hashtag: "#BeanHuntEEFFOC",
    durationDays: 7,
    max_participants: 60,
    fulfillment_mode: "check_in",
  },
  {
    id: "secret_eeffoc_drop",
    category: "discovery",
    title: "Secret EEFFOC Drop",
    emoji: "🎁",
    description: "Hidden limited campaign - explorers discover the reward after scanning.",
    reward_description: "Mystery drink (revealed at counter)",
    points_reward: 20,
    requirements: "Scan the secret QR at the counter.",
    hashtag: "#SecretEEFFOC",
    durationDays: 5,
    max_participants: 40,
    fulfillment_mode: "check_in",
  },
  {
    id: "rainy_day_eeffoc",
    category: "weather",
    title: "Rainy Day EEFFOC",
    emoji: "🌧️",
    description: "Bring people in when the weather is gloomy.",
    reward_description: "10% off + free cookie",
    points_reward: 12,
    requirements: "Check in on a rainy day (auto-detected or ask at counter).",
    hashtag: "#RainyDayEEFFOC",
    durationDays: 30,
    max_participants: 100,
    fulfillment_mode: "check_in",
  },
  {
    id: "sunny_sip_eeffoc",
    category: "weather",
    title: "Sunny Sip EEFFOC",
    emoji: "☀️",
    description: "Terrace weather, celebrate sunshine with a bright drink.",
    reward_description: "Free iced drink upgrade",
    points_reward: 12,
    requirements: "Check in on a sunny day and enjoy outdoor seating.",
    hashtag: "#SunnySipEEFFOC",
    durationDays: 30,
    max_participants: 100,
    fulfillment_mode: "check_in",
  },
  {
    id: "free_sip_friday",
    category: "weekly_ritual",
    title: "Free EEFFOC on Friday",
    emoji: "🎉",
    description: "Easy recurring Friday ritual explorers can remember.",
    reward_description: "Free filter coffee every Friday",
    points_reward: 15,
    requirements: "Check in on any Friday.",
    hashtag: "#FreeSipFriday",
    durationDays: 28,
    max_participants: 150,
    fulfillment_mode: "check_in",
  },
  {
    id: "weekly_eeffoc",
    category: "weekly_ritual",
    title: "Weekly EEFFOC",
    emoji: "📅",
    description: "One fixed day per week, pick your best slow day.",
    reward_description: "Complimentary drink on campaign day",
    points_reward: 12,
    requirements: "Visit on your chosen weekly campaign day.",
    hashtag: "#WeeklyEEFFOC",
    durationDays: 30,
    max_participants: 120,
    fulfillment_mode: "check_in",
  },
  {
    id: "creator_eeffoc",
    category: "creator",
    title: "Creator EEFFOC",
    emoji: "🎬",
    description: "For explorers with stronger social reach, higher bar, bigger reward.",
    reward_description: "Premium drink + pastry",
    points_reward: 40,
    requirements: "Reel or TikTok with café tag, 15s+, hashtag in caption.",
    hashtag: "#CreatorEEFFOC",
    durationDays: 21,
    max_participants: 40,
    fulfillment_mode: "social_proof",
    social_requirements: {
      platforms: ["tiktok", "instagram_post"],
      caption_template: "Creator EEFFOC at {shop_name} {hashtag}",
      media_hints: "Film a reel: ambience, barista, or drink reveal.",
    },
  },
  {
    id: "local_hero_eeffoc",
    category: "creator",
    title: "Local Hero EEFFOC",
    emoji: "🏠",
    description: "Community-focused, support your neighbourhood café.",
    reward_description: "Free coffee for locals",
    points_reward: 15,
    requirements: "Post about supporting local with our hashtag.",
    hashtag: "#LocalHeroEEFFOC",
    durationDays: 30,
    max_participants: 200,
    fulfillment_mode: "social_proof",
    social_requirements: {
      platforms: ["instagram_post", "facebook_post"],
      caption_template: "Supporting local at {shop_name} {hashtag}",
    },
  },
  {
    id: "study_sip_eeffoc",
    category: "classic",
    title: "Study EEFFOC",
    emoji: "📚",
    description: "Student-focused, near universities or libraries.",
    reward_description: "15% off with student ID",
    points_reward: 10,
    requirements: "Valid student ID at check-in.",
    hashtag: "#StudySipEEFFOC",
    durationDays: 30,
    max_participants: 200,
    fulfillment_mode: "check_in",
  },
  {
    id: "custom",
    category: "custom",
    title: "Custom EEFFOC",
    emoji: "✨",
    description: "Design your own EEFFOC moment from scratch.",
    reward_description: "",
    points_reward: 10,
    requirements: "",
    hashtag: "#WeGiveEEFFOC",
    durationDays: 14,
    max_participants: 100,
    fulfillment_mode: "check_in",
  },
];

export function templatesByCategory(category: EeffocTemplateCategory): EeffocTemplate[] {
  return EEFFOC_TEMPLATES.filter((t) => t.category === category);
}

export const EEFFOC_TEMPLATE_CATEGORIES: EeffocTemplateCategory[] = [
  "classic",
  "limited_drop",
  "time_window",
  "friend",
  "repeat_visitor",
  "discovery",
  "premium",
  "weather",
  "weekly_ritual",
  "creator",
  "custom",
];
