/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ListRouteImport } from './routes/list'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DataProcessingRouteImport } from './routes/data-processing'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoffeeSlugRouteImport } from './routes/coffee.$slug'
import { Route as CityCityRouteImport } from './routes/city.$city'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedExplorerRouteRouteImport } from './routes/_authenticated/_explorer/route'
import { Route as AuthenticatedPartnerIndexRouteImport } from './routes/_authenticated/partner.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as AuthenticatedPartnerVerifyRouteImport } from './routes/_authenticated/partner.verify'
import { Route as AuthenticatedPartnerSubmissionsRouteImport } from './routes/_authenticated/partner.submissions'
import { Route as AuthenticatedPartnerShopRouteImport } from './routes/_authenticated/partner.shop'
import { Route as AuthenticatedPartnerSettingsRouteImport } from './routes/_authenticated/partner.settings'
import { Route as AuthenticatedPartnerRewardsRouteImport } from './routes/_authenticated/partner.rewards'
import { Route as AuthenticatedPartnerCampaignsRouteImport } from './routes/_authenticated/partner.campaigns'
import { Route as AuthenticatedPartnerBillingRouteImport } from './routes/_authenticated/partner.billing'
import { Route as AuthenticatedPartnerAnalyticsRouteImport } from './routes/_authenticated/partner.analytics'
import { Route as AuthenticatedGiftTokenRouteImport } from './routes/_authenticated/gift.$token'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTrustRouteImport } from './routes/_authenticated/admin.trust'
import { Route as AuthenticatedAdminShopsRouteImport } from './routes/_authenticated/admin.shops'
import { Route as AuthenticatedAdminRevenueRouteImport } from './routes/_authenticated/admin.revenue'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated/admin.campaigns'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedExplorerWalletRouteImport } from './routes/_authenticated/_explorer/wallet'
import { Route as AuthenticatedExplorerRadarRouteImport } from './routes/_authenticated/_explorer/radar'
import { Route as AuthenticatedExplorerProfileRouteImport } from './routes/_authenticated/_explorer/profile'
import { Route as AuthenticatedExplorerPassportRouteImport } from './routes/_authenticated/_explorer/passport'
import { Route as AuthenticatedExplorerOnboardingRouteImport } from './routes/_authenticated/_explorer/onboarding'
import { Route as AuthenticatedExplorerMomentsRouteImport } from './routes/_authenticated/_explorer/moments'
import { Route as AuthenticatedExplorerLeaderboardRouteImport } from './routes/_authenticated/_explorer/leaderboard'
import { Route as AuthenticatedExplorerExploreRouteImport } from './routes/_authenticated/_explorer/explore'
import { Route as AuthenticatedExplorerCrewRouteImport } from './routes/_authenticated/_explorer/crew'
import { Route as AuthenticatedExplorerCrawlsRouteImport } from './routes/_authenticated/_explorer/crawls'
import { Route as AuthenticatedExplorerCampaignsRouteImport } from './routes/_authenticated/_explorer/campaigns'
import { Route as AuthenticatedExplorerCampaignMapRouteImport } from './routes/_authenticated/_explorer/campaign-map'
import { Route as AuthenticatedExplorerCrawlsSlugRouteImport } from './routes/_authenticated/_explorer/crawls.$slug'
import { Route as AuthenticatedExplorerCampaignIdRouteImport } from './routes/_authenticated/_explorer/campaign.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DataProcessingRoute = DataProcessingRouteImport.update({
  id: '/data-processing',
  path: '/data-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeeSlugRoute = CoffeeSlugRouteImport.update({
  id: '/coffee/$slug',
  path: '/coffee/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCityRoute = CityCityRouteImport.update({
  id: '/city/$city',
  path: '/city/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExplorerRouteRoute =
  AuthenticatedExplorerRouteRouteImport.update({
    id: '/_explorer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnerIndexRoute =
  AuthenticatedPartnerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPartnerVerifyRoute =
  AuthenticatedPartnerVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerSubmissionsRoute =
  AuthenticatedPartnerSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerShopRoute =
  AuthenticatedPartnerShopRouteImport.update({
    id: '/shop',
    path: '/shop',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerSettingsRoute =
  AuthenticatedPartnerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerRewardsRoute =
  AuthenticatedPartnerRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerCampaignsRoute =
  AuthenticatedPartnerCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerBillingRoute =
  AuthenticatedPartnerBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerAnalyticsRoute =
  AuthenticatedPartnerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedGiftTokenRoute = AuthenticatedGiftTokenRouteImport.update({
  id: '/gift/$token',
  path: '/gift/$token',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTrustRoute = AuthenticatedAdminTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminShopsRoute = AuthenticatedAdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRevenueRoute =
  AuthenticatedAdminRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedExplorerWalletRoute =
  AuthenticatedExplorerWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)
const AuthenticatedExplorerRadarRoute =
  AuthenticatedExplorerRadarRouteImport.update({
    id: '/radar',
    path: '/radar',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)
const AuthenticatedExplorerProfileRoute =
  AuthenticatedExplorerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)
const AuthenticatedExplorerPassportRoute =
  AuthenticatedExplorerPassportRouteImport.update({
    id: '/passport',
    path: '/passport',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)
const AuthenticatedExplorerOnboardingRoute =
  AuthenticatedExplorerOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)
const AuthenticatedExplorerMomentsRoute =
  AuthenticatedExplorerMomentsRouteImport.update({
    id: '/moments',
    path: '/moments',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)
const AuthenticatedExplorerLeaderboardRoute =
  AuthenticatedExplorerLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)
const AuthenticatedExplorerExploreRoute =
  AuthenticatedExplorerExploreRouteImport.update({
    id: '/explore',
    path: '/explore',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)
const AuthenticatedExplorerCrewRoute =
  AuthenticatedExplorerCrewRouteImport.update({
    id: '/crew',
    path: '/crew',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)
const AuthenticatedExplorerCrawlsRoute =
  AuthenticatedExplorerCrawlsRouteImport.update({
    id: '/crawls',
    path: '/crawls',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)
const AuthenticatedExplorerCampaignsRoute =
  AuthenticatedExplorerCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)
const AuthenticatedExplorerCampaignMapRoute =
  AuthenticatedExplorerCampaignMapRouteImport.update({
    id: '/campaign-map',
    path: '/campaign-map',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)
const AuthenticatedExplorerCrawlsSlugRoute =
  AuthenticatedExplorerCrawlsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedExplorerCrawlsRoute,
  } as any)
const AuthenticatedExplorerCampaignIdRoute =
  AuthenticatedExplorerCampaignIdRouteImport.update({
    id: '/campaign/$id',
    path: '/campaign/$id',
    getParentRoute: () => AuthenticatedExplorerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRouteWithChildren
  '/community': typeof CommunityRoute
  '/cookies': typeof CookiesRoute
  '/data-processing': typeof DataProcessingRoute
  '/impressum': typeof ImpressumRoute
  '/list': typeof ListRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/rewards': typeof RewardsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/city/$city': typeof CityCityRoute
  '/coffee/$slug': typeof CoffeeSlugRoute
  '/campaign-map': typeof AuthenticatedExplorerCampaignMapRoute
  '/campaigns': typeof AuthenticatedExplorerCampaignsRoute
  '/crawls': typeof AuthenticatedExplorerCrawlsRouteWithChildren
  '/crew': typeof AuthenticatedExplorerCrewRoute
  '/explore': typeof AuthenticatedExplorerExploreRoute
  '/leaderboard': typeof AuthenticatedExplorerLeaderboardRoute
  '/moments': typeof AuthenticatedExplorerMomentsRoute
  '/onboarding': typeof AuthenticatedExplorerOnboardingRoute
  '/passport': typeof AuthenticatedExplorerPassportRoute
  '/profile': typeof AuthenticatedExplorerProfileRoute
  '/radar': typeof AuthenticatedExplorerRadarRoute
  '/wallet': typeof AuthenticatedExplorerWalletRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/shops': typeof AuthenticatedAdminShopsRoute
  '/admin/trust': typeof AuthenticatedAdminTrustRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/gift/$token': typeof AuthenticatedGiftTokenRoute
  '/partner/analytics': typeof AuthenticatedPartnerAnalyticsRoute
  '/partner/billing': typeof AuthenticatedPartnerBillingRoute
  '/partner/campaigns': typeof AuthenticatedPartnerCampaignsRoute
  '/partner/rewards': typeof AuthenticatedPartnerRewardsRoute
  '/partner/settings': typeof AuthenticatedPartnerSettingsRoute
  '/partner/shop': typeof AuthenticatedPartnerShopRoute
  '/partner/submissions': typeof AuthenticatedPartnerSubmissionsRoute
  '/partner/verify': typeof AuthenticatedPartnerVerifyRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/partner/': typeof AuthenticatedPartnerIndexRoute
  '/campaign/$id': typeof AuthenticatedExplorerCampaignIdRoute
  '/crawls/$slug': typeof AuthenticatedExplorerCrawlsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRouteWithChildren
  '/community': typeof CommunityRoute
  '/cookies': typeof CookiesRoute
  '/data-processing': typeof DataProcessingRoute
  '/impressum': typeof ImpressumRoute
  '/list': typeof ListRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/rewards': typeof RewardsRoute
  '/terms': typeof TermsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/city/$city': typeof CityCityRoute
  '/coffee/$slug': typeof CoffeeSlugRoute
  '/campaign-map': typeof AuthenticatedExplorerCampaignMapRoute
  '/campaigns': typeof AuthenticatedExplorerCampaignsRoute
  '/crawls': typeof AuthenticatedExplorerCrawlsRouteWithChildren
  '/crew': typeof AuthenticatedExplorerCrewRoute
  '/explore': typeof AuthenticatedExplorerExploreRoute
  '/leaderboard': typeof AuthenticatedExplorerLeaderboardRoute
  '/moments': typeof AuthenticatedExplorerMomentsRoute
  '/onboarding': typeof AuthenticatedExplorerOnboardingRoute
  '/passport': typeof AuthenticatedExplorerPassportRoute
  '/profile': typeof AuthenticatedExplorerProfileRoute
  '/radar': typeof AuthenticatedExplorerRadarRoute
  '/wallet': typeof AuthenticatedExplorerWalletRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/shops': typeof AuthenticatedAdminShopsRoute
  '/admin/trust': typeof AuthenticatedAdminTrustRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/gift/$token': typeof AuthenticatedGiftTokenRoute
  '/partner/analytics': typeof AuthenticatedPartnerAnalyticsRoute
  '/partner/billing': typeof AuthenticatedPartnerBillingRoute
  '/partner/campaigns': typeof AuthenticatedPartnerCampaignsRoute
  '/partner/rewards': typeof AuthenticatedPartnerRewardsRoute
  '/partner/settings': typeof AuthenticatedPartnerSettingsRoute
  '/partner/shop': typeof AuthenticatedPartnerShopRoute
  '/partner/submissions': typeof AuthenticatedPartnerSubmissionsRoute
  '/partner/verify': typeof AuthenticatedPartnerVerifyRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/partner': typeof AuthenticatedPartnerIndexRoute
  '/campaign/$id': typeof AuthenticatedExplorerCampaignIdRoute
  '/crawls/$slug': typeof AuthenticatedExplorerCrawlsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRouteWithChildren
  '/community': typeof CommunityRoute
  '/cookies': typeof CookiesRoute
  '/data-processing': typeof DataProcessingRoute
  '/impressum': typeof ImpressumRoute
  '/list': typeof ListRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/rewards': typeof RewardsRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_explorer': typeof AuthenticatedExplorerRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/city/$city': typeof CityCityRoute
  '/coffee/$slug': typeof CoffeeSlugRoute
  '/_authenticated/_explorer/campaign-map': typeof AuthenticatedExplorerCampaignMapRoute
  '/_authenticated/_explorer/campaigns': typeof AuthenticatedExplorerCampaignsRoute
  '/_authenticated/_explorer/crawls': typeof AuthenticatedExplorerCrawlsRouteWithChildren
  '/_authenticated/_explorer/crew': typeof AuthenticatedExplorerCrewRoute
  '/_authenticated/_explorer/explore': typeof AuthenticatedExplorerExploreRoute
  '/_authenticated/_explorer/leaderboard': typeof AuthenticatedExplorerLeaderboardRoute
  '/_authenticated/_explorer/moments': typeof AuthenticatedExplorerMomentsRoute
  '/_authenticated/_explorer/onboarding': typeof AuthenticatedExplorerOnboardingRoute
  '/_authenticated/_explorer/passport': typeof AuthenticatedExplorerPassportRoute
  '/_authenticated/_explorer/profile': typeof AuthenticatedExplorerProfileRoute
  '/_authenticated/_explorer/radar': typeof AuthenticatedExplorerRadarRoute
  '/_authenticated/_explorer/wallet': typeof AuthenticatedExplorerWalletRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/_authenticated/admin/shops': typeof AuthenticatedAdminShopsRoute
  '/_authenticated/admin/trust': typeof AuthenticatedAdminTrustRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/gift/$token': typeof AuthenticatedGiftTokenRoute
  '/_authenticated/partner/analytics': typeof AuthenticatedPartnerAnalyticsRoute
  '/_authenticated/partner/billing': typeof AuthenticatedPartnerBillingRoute
  '/_authenticated/partner/campaigns': typeof AuthenticatedPartnerCampaignsRoute
  '/_authenticated/partner/rewards': typeof AuthenticatedPartnerRewardsRoute
  '/_authenticated/partner/settings': typeof AuthenticatedPartnerSettingsRoute
  '/_authenticated/partner/shop': typeof AuthenticatedPartnerShopRoute
  '/_authenticated/partner/submissions': typeof AuthenticatedPartnerSubmissionsRoute
  '/_authenticated/partner/verify': typeof AuthenticatedPartnerVerifyRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/partner/': typeof AuthenticatedPartnerIndexRoute
  '/_authenticated/_explorer/campaign/$id': typeof AuthenticatedExplorerCampaignIdRoute
  '/_authenticated/_explorer/crawls/$slug': typeof AuthenticatedExplorerCrawlsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/community'
    | '/cookies'
    | '/data-processing'
    | '/impressum'
    | '/list'
    | '/partners'
    | '/privacy'
    | '/rewards'
    | '/terms'
    | '/admin'
    | '/partner'
    | '/auth/forgot'
    | '/auth/reset'
    | '/city/$city'
    | '/coffee/$slug'
    | '/campaign-map'
    | '/campaigns'
    | '/crawls'
    | '/crew'
    | '/explore'
    | '/leaderboard'
    | '/moments'
    | '/onboarding'
    | '/passport'
    | '/profile'
    | '/radar'
    | '/wallet'
    | '/admin/analytics'
    | '/admin/campaigns'
    | '/admin/moderation'
    | '/admin/partners'
    | '/admin/revenue'
    | '/admin/shops'
    | '/admin/trust'
    | '/admin/users'
    | '/gift/$token'
    | '/partner/analytics'
    | '/partner/billing'
    | '/partner/campaigns'
    | '/partner/rewards'
    | '/partner/settings'
    | '/partner/shop'
    | '/partner/submissions'
    | '/partner/verify'
    | '/api/stripe/webhook'
    | '/admin/'
    | '/partner/'
    | '/campaign/$id'
    | '/crawls/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/community'
    | '/cookies'
    | '/data-processing'
    | '/impressum'
    | '/list'
    | '/partners'
    | '/privacy'
    | '/rewards'
    | '/terms'
    | '/auth/forgot'
    | '/auth/reset'
    | '/city/$city'
    | '/coffee/$slug'
    | '/campaign-map'
    | '/campaigns'
    | '/crawls'
    | '/crew'
    | '/explore'
    | '/leaderboard'
    | '/moments'
    | '/onboarding'
    | '/passport'
    | '/profile'
    | '/radar'
    | '/wallet'
    | '/admin/analytics'
    | '/admin/campaigns'
    | '/admin/moderation'
    | '/admin/partners'
    | '/admin/revenue'
    | '/admin/shops'
    | '/admin/trust'
    | '/admin/users'
    | '/gift/$token'
    | '/partner/analytics'
    | '/partner/billing'
    | '/partner/campaigns'
    | '/partner/rewards'
    | '/partner/settings'
    | '/partner/shop'
    | '/partner/submissions'
    | '/partner/verify'
    | '/api/stripe/webhook'
    | '/admin'
    | '/partner'
    | '/campaign/$id'
    | '/crawls/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accessibility'
    | '/auth'
    | '/community'
    | '/cookies'
    | '/data-processing'
    | '/impressum'
    | '/list'
    | '/partners'
    | '/privacy'
    | '/rewards'
    | '/terms'
    | '/_authenticated/_explorer'
    | '/_authenticated/admin'
    | '/_authenticated/partner'
    | '/auth/forgot'
    | '/auth/reset'
    | '/city/$city'
    | '/coffee/$slug'
    | '/_authenticated/_explorer/campaign-map'
    | '/_authenticated/_explorer/campaigns'
    | '/_authenticated/_explorer/crawls'
    | '/_authenticated/_explorer/crew'
    | '/_authenticated/_explorer/explore'
    | '/_authenticated/_explorer/leaderboard'
    | '/_authenticated/_explorer/moments'
    | '/_authenticated/_explorer/onboarding'
    | '/_authenticated/_explorer/passport'
    | '/_authenticated/_explorer/profile'
    | '/_authenticated/_explorer/radar'
    | '/_authenticated/_explorer/wallet'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/revenue'
    | '/_authenticated/admin/shops'
    | '/_authenticated/admin/trust'
    | '/_authenticated/admin/users'
    | '/_authenticated/gift/$token'
    | '/_authenticated/partner/analytics'
    | '/_authenticated/partner/billing'
    | '/_authenticated/partner/campaigns'
    | '/_authenticated/partner/rewards'
    | '/_authenticated/partner/settings'
    | '/_authenticated/partner/shop'
    | '/_authenticated/partner/submissions'
    | '/_authenticated/partner/verify'
    | '/api/stripe/webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/partner/'
    | '/_authenticated/_explorer/campaign/$id'
    | '/_authenticated/_explorer/crawls/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  CookiesRoute: typeof CookiesRoute
  DataProcessingRoute: typeof DataProcessingRoute
  ImpressumRoute: typeof ImpressumRoute
  ListRoute: typeof ListRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  RewardsRoute: typeof RewardsRoute
  TermsRoute: typeof TermsRoute
  CityCityRoute: typeof CityCityRoute
  CoffeeSlugRoute: typeof CoffeeSlugRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-processing': {
      id: '/data-processing'
      path: '/data-processing'
      fullPath: '/data-processing'
      preLoaderRoute: typeof DataProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffee/$slug': {
      id: '/coffee/$slug'
      path: '/coffee/$slug'
      fullPath: '/coffee/$slug'
      preLoaderRoute: typeof CoffeeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$city': {
      id: '/city/$city'
      path: '/city/$city'
      fullPath: '/city/$city'
      preLoaderRoute: typeof CityCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_explorer': {
      id: '/_authenticated/_explorer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedExplorerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner/': {
      id: '/_authenticated/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof AuthenticatedPartnerIndexRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/partner/verify': {
      id: '/_authenticated/partner/verify'
      path: '/verify'
      fullPath: '/partner/verify'
      preLoaderRoute: typeof AuthenticatedPartnerVerifyRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/submissions': {
      id: '/_authenticated/partner/submissions'
      path: '/submissions'
      fullPath: '/partner/submissions'
      preLoaderRoute: typeof AuthenticatedPartnerSubmissionsRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/shop': {
      id: '/_authenticated/partner/shop'
      path: '/shop'
      fullPath: '/partner/shop'
      preLoaderRoute: typeof AuthenticatedPartnerShopRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/settings': {
      id: '/_authenticated/partner/settings'
      path: '/settings'
      fullPath: '/partner/settings'
      preLoaderRoute: typeof AuthenticatedPartnerSettingsRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/rewards': {
      id: '/_authenticated/partner/rewards'
      path: '/rewards'
      fullPath: '/partner/rewards'
      preLoaderRoute: typeof AuthenticatedPartnerRewardsRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/campaigns': {
      id: '/_authenticated/partner/campaigns'
      path: '/campaigns'
      fullPath: '/partner/campaigns'
      preLoaderRoute: typeof AuthenticatedPartnerCampaignsRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/billing': {
      id: '/_authenticated/partner/billing'
      path: '/billing'
      fullPath: '/partner/billing'
      preLoaderRoute: typeof AuthenticatedPartnerBillingRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/analytics': {
      id: '/_authenticated/partner/analytics'
      path: '/analytics'
      fullPath: '/partner/analytics'
      preLoaderRoute: typeof AuthenticatedPartnerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/gift/$token': {
      id: '/_authenticated/gift/$token'
      path: '/gift/$token'
      fullPath: '/gift/$token'
      preLoaderRoute: typeof AuthenticatedGiftTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trust': {
      id: '/_authenticated/admin/trust'
      path: '/trust'
      fullPath: '/admin/trust'
      preLoaderRoute: typeof AuthenticatedAdminTrustRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/shops': {
      id: '/_authenticated/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AuthenticatedAdminShopsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/revenue': {
      id: '/_authenticated/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AuthenticatedAdminRevenueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_explorer/wallet': {
      id: '/_authenticated/_explorer/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedExplorerWalletRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
    '/_authenticated/_explorer/radar': {
      id: '/_authenticated/_explorer/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedExplorerRadarRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
    '/_authenticated/_explorer/profile': {
      id: '/_authenticated/_explorer/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedExplorerProfileRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
    '/_authenticated/_explorer/passport': {
      id: '/_authenticated/_explorer/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof AuthenticatedExplorerPassportRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
    '/_authenticated/_explorer/onboarding': {
      id: '/_authenticated/_explorer/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedExplorerOnboardingRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
    '/_authenticated/_explorer/moments': {
      id: '/_authenticated/_explorer/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof AuthenticatedExplorerMomentsRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
    '/_authenticated/_explorer/leaderboard': {
      id: '/_authenticated/_explorer/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedExplorerLeaderboardRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
    '/_authenticated/_explorer/explore': {
      id: '/_authenticated/_explorer/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExplorerExploreRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
    '/_authenticated/_explorer/crew': {
      id: '/_authenticated/_explorer/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof AuthenticatedExplorerCrewRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
    '/_authenticated/_explorer/crawls': {
      id: '/_authenticated/_explorer/crawls'
      path: '/crawls'
      fullPath: '/crawls'
      preLoaderRoute: typeof AuthenticatedExplorerCrawlsRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
    '/_authenticated/_explorer/campaigns': {
      id: '/_authenticated/_explorer/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedExplorerCampaignsRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
    '/_authenticated/_explorer/campaign-map': {
      id: '/_authenticated/_explorer/campaign-map'
      path: '/campaign-map'
      fullPath: '/campaign-map'
      preLoaderRoute: typeof AuthenticatedExplorerCampaignMapRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
    '/_authenticated/_explorer/crawls/$slug': {
      id: '/_authenticated/_explorer/crawls/$slug'
      path: '/$slug'
      fullPath: '/crawls/$slug'
      preLoaderRoute: typeof AuthenticatedExplorerCrawlsSlugRouteImport
      parentRoute: typeof AuthenticatedExplorerCrawlsRoute
    }
    '/_authenticated/_explorer/campaign/$id': {
      id: '/_authenticated/_explorer/campaign/$id'
      path: '/campaign/$id'
      fullPath: '/campaign/$id'
      preLoaderRoute: typeof AuthenticatedExplorerCampaignIdRouteImport
      parentRoute: typeof AuthenticatedExplorerRouteRoute
    }
  }
}

interface AuthenticatedExplorerCrawlsRouteChildren {
  AuthenticatedExplorerCrawlsSlugRoute: typeof AuthenticatedExplorerCrawlsSlugRoute
}

const AuthenticatedExplorerCrawlsRouteChildren: AuthenticatedExplorerCrawlsRouteChildren =
  {
    AuthenticatedExplorerCrawlsSlugRoute: AuthenticatedExplorerCrawlsSlugRoute,
  }

const AuthenticatedExplorerCrawlsRouteWithChildren =
  AuthenticatedExplorerCrawlsRoute._addFileChildren(
    AuthenticatedExplorerCrawlsRouteChildren,
  )

interface AuthenticatedExplorerRouteRouteChildren {
  AuthenticatedExplorerCampaignMapRoute: typeof AuthenticatedExplorerCampaignMapRoute
  AuthenticatedExplorerCampaignsRoute: typeof AuthenticatedExplorerCampaignsRoute
  AuthenticatedExplorerCrawlsRoute: typeof AuthenticatedExplorerCrawlsRouteWithChildren
  AuthenticatedExplorerCrewRoute: typeof AuthenticatedExplorerCrewRoute
  AuthenticatedExplorerExploreRoute: typeof AuthenticatedExplorerExploreRoute
  AuthenticatedExplorerLeaderboardRoute: typeof AuthenticatedExplorerLeaderboardRoute
  AuthenticatedExplorerMomentsRoute: typeof AuthenticatedExplorerMomentsRoute
  AuthenticatedExplorerOnboardingRoute: typeof AuthenticatedExplorerOnboardingRoute
  AuthenticatedExplorerPassportRoute: typeof AuthenticatedExplorerPassportRoute
  AuthenticatedExplorerProfileRoute: typeof AuthenticatedExplorerProfileRoute
  AuthenticatedExplorerRadarRoute: typeof AuthenticatedExplorerRadarRoute
  AuthenticatedExplorerWalletRoute: typeof AuthenticatedExplorerWalletRoute
  AuthenticatedExplorerCampaignIdRoute: typeof AuthenticatedExplorerCampaignIdRoute
}

const AuthenticatedExplorerRouteRouteChildren: AuthenticatedExplorerRouteRouteChildren =
  {
    AuthenticatedExplorerCampaignMapRoute:
      AuthenticatedExplorerCampaignMapRoute,
    AuthenticatedExplorerCampaignsRoute: AuthenticatedExplorerCampaignsRoute,
    AuthenticatedExplorerCrawlsRoute:
      AuthenticatedExplorerCrawlsRouteWithChildren,
    AuthenticatedExplorerCrewRoute: AuthenticatedExplorerCrewRoute,
    AuthenticatedExplorerExploreRoute: AuthenticatedExplorerExploreRoute,
    AuthenticatedExplorerLeaderboardRoute:
      AuthenticatedExplorerLeaderboardRoute,
    AuthenticatedExplorerMomentsRoute: AuthenticatedExplorerMomentsRoute,
    AuthenticatedExplorerOnboardingRoute: AuthenticatedExplorerOnboardingRoute,
    AuthenticatedExplorerPassportRoute: AuthenticatedExplorerPassportRoute,
    AuthenticatedExplorerProfileRoute: AuthenticatedExplorerProfileRoute,
    AuthenticatedExplorerRadarRoute: AuthenticatedExplorerRadarRoute,
    AuthenticatedExplorerWalletRoute: AuthenticatedExplorerWalletRoute,
    AuthenticatedExplorerCampaignIdRoute: AuthenticatedExplorerCampaignIdRoute,
  }

const AuthenticatedExplorerRouteRouteWithChildren =
  AuthenticatedExplorerRouteRoute._addFileChildren(
    AuthenticatedExplorerRouteRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminRevenueRoute: typeof AuthenticatedAdminRevenueRoute
  AuthenticatedAdminShopsRoute: typeof AuthenticatedAdminShopsRoute
  AuthenticatedAdminTrustRoute: typeof AuthenticatedAdminTrustRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminRevenueRoute: AuthenticatedAdminRevenueRoute,
  AuthenticatedAdminShopsRoute: AuthenticatedAdminShopsRoute,
  AuthenticatedAdminTrustRoute: AuthenticatedAdminTrustRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPartnerRouteChildren {
  AuthenticatedPartnerAnalyticsRoute: typeof AuthenticatedPartnerAnalyticsRoute
  AuthenticatedPartnerBillingRoute: typeof AuthenticatedPartnerBillingRoute
  AuthenticatedPartnerCampaignsRoute: typeof AuthenticatedPartnerCampaignsRoute
  AuthenticatedPartnerRewardsRoute: typeof AuthenticatedPartnerRewardsRoute
  AuthenticatedPartnerSettingsRoute: typeof AuthenticatedPartnerSettingsRoute
  AuthenticatedPartnerShopRoute: typeof AuthenticatedPartnerShopRoute
  AuthenticatedPartnerSubmissionsRoute: typeof AuthenticatedPartnerSubmissionsRoute
  AuthenticatedPartnerVerifyRoute: typeof AuthenticatedPartnerVerifyRoute
  AuthenticatedPartnerIndexRoute: typeof AuthenticatedPartnerIndexRoute
}

const AuthenticatedPartnerRouteChildren: AuthenticatedPartnerRouteChildren = {
  AuthenticatedPartnerAnalyticsRoute: AuthenticatedPartnerAnalyticsRoute,
  AuthenticatedPartnerBillingRoute: AuthenticatedPartnerBillingRoute,
  AuthenticatedPartnerCampaignsRoute: AuthenticatedPartnerCampaignsRoute,
  AuthenticatedPartnerRewardsRoute: AuthenticatedPartnerRewardsRoute,
  AuthenticatedPartnerSettingsRoute: AuthenticatedPartnerSettingsRoute,
  AuthenticatedPartnerShopRoute: AuthenticatedPartnerShopRoute,
  AuthenticatedPartnerSubmissionsRoute: AuthenticatedPartnerSubmissionsRoute,
  AuthenticatedPartnerVerifyRoute: AuthenticatedPartnerVerifyRoute,
  AuthenticatedPartnerIndexRoute: AuthenticatedPartnerIndexRoute,
}

const AuthenticatedPartnerRouteWithChildren =
  AuthenticatedPartnerRoute._addFileChildren(AuthenticatedPartnerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedExplorerRouteRoute: typeof AuthenticatedExplorerRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRouteWithChildren
  AuthenticatedGiftTokenRoute: typeof AuthenticatedGiftTokenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedExplorerRouteRoute: AuthenticatedExplorerRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRouteWithChildren,
  AuthenticatedGiftTokenRoute: AuthenticatedGiftTokenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRouteWithChildren,
  CommunityRoute: CommunityRoute,
  CookiesRoute: CookiesRoute,
  DataProcessingRoute: DataProcessingRoute,
  ImpressumRoute: ImpressumRoute,
  ListRoute: ListRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  RewardsRoute: RewardsRoute,
  TermsRoute: TermsRoute,
  CityCityRoute: CityCityRoute,
  CoffeeSlugRoute: CoffeeSlugRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
